apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: gpa-validator
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lKQU15M2dxY05QNmo4TUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURIWmhiR2xrWVhSdmNsOWpZVEFnRncweU1UQTFNVFV4TXpNNE5EWmFHQTh5TWprMU1ESXlPREV6TXpnMApObG93RnpFVk1CTUdBMVVFQXd3TWRtRnNhV1JoZEc5eVgyTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFxdm91RGppWFFKc3V6VUk4VlBHQUlYQXl0YXhMeGlLQVpzQVE2SUx1dlRwTUNnaTAKWTQwdktGcGdBU29zTTBYQUg4VWlHeWRXYldQd21uMi9qc2tKMjk5VGhPdnN4VzBHYU1BNHpqd3NHNUU3ZUZyUQp0RGlWZVd5S1k0MWV0YVpFRWpPNjB5TVdTTTNjL2hyeDJkdm4yblZ3WGJ5c3FXV1ZxYjgvM2NkRU5OTTVmUXNRClp0WEQyNG1qQUMya2d2MjVVSHNranNoampoQ3NDeXlIWVRqNGl2dkZFUG9hSTN6M2ZKSng2NmgyazB4WXhGQUwKc0VkU1ptRFJBZHNheTBacExEbjZ1ZU42NzVIR0dxMGx2SmVRRGR6Y2l2RnNYM25pL3owU1ExdW5MWDMvMWl6bApWOWNXaXlOOHlXb1BjbUQyejVHUjJKMnpoL28vTzNaaFNsNXQwUUlEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVCjZZemhjR0U5dkZJN0FyaHdDTUNaQXMydFBFOHdId1lEVlIwakJCZ3dGb0FVNll6aGNHRTl2Rkk3QXJod0NNQ1oKQXMydFBFOHdEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxPd2RHL0ZGbmN0UwpyWUhVWnhyZUV4Nm1BakdxRW9ZaE92WUpySU5Ec29qRzZsL2Z5cnRmOG5POXhEb2J0K0x1eW5rdFp0WVlqQ1F4CjJDV0VvbDIvN1dyczRjUEpXV0NQQUp6NGNyYjRVclNGWDhUTmJWZllVWDYxNHMrVUtEZDcvZmhQa0toVUFpaGwKeFQ3K3hJU3QyQi9MbnYwbGRNV0RzTlcwSTNYUFFqZURnM2lFSGVONjQxbnNmTjVtR1dRblc2RDJaek9lL3dmVgpVSzRVS3ZlSFFsVlNjZjFSbzVSOFQ1TkMwQVNMUW1DSUVDT2JSaDFBSjA0Y3l0MGdhYU5CNUNQaHlXVDdoTE9SCmxhVEdsWnVTOGt2WVd5ZTM1UEM2N3Z0RWRYRXowcExSdTNpVHBoMEkrbGZucWRPVDZkQjBRa0VyT1ZlNFZ2UHYKaTF4SGVXa1dzQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        namespace: kube-system
        name: gpa-validator
        path: /mutate
    failurePolicy: Ignore
    name: gpa-validator.autoscaling.bcs.dev
    namespaceSelector:
      matchExpressions:
        - key: ns
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - "autoscaling.bcs.dev"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10