
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.0
  creationTimestamp: null
  name: listeners.networkextension.bkbcs.tencent.com
spec:
  group: networkextension.bkbcs.tencent.com
  names:
    kind: Listener
    listKind: ListenerList
    plural: listeners
    singular: listener
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: status
      type: string
    - jsonPath: .spec.protocol
      name: protocol
      type: string
    - jsonPath: .spec.port
      name: port
      type: integer
    - jsonPath: .spec.endPort
      name: endPort
      type: integer
    - jsonPath: .spec.loadbalancerID
      name: loadbalancerID
      type: string
    - jsonPath: .status.ingress
      name: ingress
      type: string
    - jsonPath: .status.portpool
      name: portpool
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Listener is the Schema for the listeners API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ListenerSpec defines the desired state of Listener
            properties:
              certificate:
                description: IngressListenerCertificate certificate configs for listener
                properties:
                  certCaID:
                    type: string
                  certID:
                    type: string
                  mode:
                    type: string
                type: object
              endPort:
                type: integer
              listenerAttribute:
                description: IngressListenerAttribute attribute for listener
                properties:
                  awsAttributes:
                    description: aws targetGroup attributes, https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyTargetGroupAttributes.html
                    items:
                      description: AWSAttribute define aws target group attribute
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  backendInsecure:
                    description: BackendInsecure specifies whether to enable insecure
                      access to the backend.
                    type: boolean
                  healthCheck:
                    description: ListenerHealthCheck health check setting for listener
                    properties:
                      enabled:
                        type: boolean
                      healthCheckPort:
                        type: integer
                      healthCheckProtocol:
                        type: string
                      healthNum:
                        type: integer
                      httpCheckMethod:
                        type: string
                      httpCheckPath:
                        type: string
                      httpCode:
                        type: integer
                      httpCodeValues:
                        description: HTTPCodeValues specifies a set of HTTP response
                          status codes of health check. You can specify multiple values
                          (for example, "200,202") or a range of values (for example,
                          "200-299"). https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.17.0/types#Matcher
                        type: string
                      intervalTime:
                        type: integer
                      timeout:
                        type: integer
                      unHealthNum:
                        type: integer
                    type: object
                  keepAliveEnable:
                    type: integer
                  lbPolicy:
                    type: string
                  maxRate:
                    description: MaxRate specifies the maximum number of connections
                      per second allowed for every target instance.
                    type: integer
                  sessionTime:
                    type: integer
                  sniSwitch:
                    type: integer
                type: object
              loadbalancerID:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                type: string
              port:
                type: integer
              protocol:
                type: string
              rules:
                items:
                  description: ListenerRule route rule for listener
                  properties:
                    certificate:
                      description: IngressListenerCertificate certificate configs
                        for listener
                      properties:
                        certCaID:
                          type: string
                        certID:
                          type: string
                        mode:
                          type: string
                      type: object
                    domain:
                      type: string
                    listenerAttribute:
                      description: IngressListenerAttribute attribute for listener
                      properties:
                        awsAttributes:
                          description: aws targetGroup attributes, https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyTargetGroupAttributes.html
                          items:
                            description: AWSAttribute define aws target group attribute
                            properties:
                              key:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        backendInsecure:
                          description: BackendInsecure specifies whether to enable
                            insecure access to the backend.
                          type: boolean
                        healthCheck:
                          description: ListenerHealthCheck health check setting for
                            listener
                          properties:
                            enabled:
                              type: boolean
                            healthCheckPort:
                              type: integer
                            healthCheckProtocol:
                              type: string
                            healthNum:
                              type: integer
                            httpCheckMethod:
                              type: string
                            httpCheckPath:
                              type: string
                            httpCode:
                              type: integer
                            httpCodeValues:
                              description: HTTPCodeValues specifies a set of HTTP
                                response status codes of health check. You can specify
                                multiple values (for example, "200,202") or a range
                                of values (for example, "200-299"). https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.17.0/types#Matcher
                              type: string
                            intervalTime:
                              type: integer
                            timeout:
                              type: integer
                            unHealthNum:
                              type: integer
                          type: object
                        keepAliveEnable:
                          type: integer
                        lbPolicy:
                          type: string
                        maxRate:
                          description: MaxRate specifies the maximum number of connections
                            per second allowed for every target instance.
                          type: integer
                        sessionTime:
                          type: integer
                        sniSwitch:
                          type: integer
                      type: object
                    path:
                      type: string
                    ruleID:
                      type: string
                    targetGroup:
                      description: ListenerTargetGroup backend set for listener
                      properties:
                        backends:
                          items:
                            description: ListenerBackend info for backend
                            properties:
                              IP:
                                type: string
                              port:
                                type: integer
                              weight:
                                type: integer
                            required:
                            - IP
                            - port
                            - weight
                            type: object
                          type: array
                        protocol:
                          type: string
                        targetGroupID:
                          type: string
                        targetGroupName:
                          type: string
                      type: object
                  type: object
                type: array
              targetGroup:
                description: ListenerTargetGroup backend set for listener
                properties:
                  backends:
                    items:
                      description: ListenerBackend info for backend
                      properties:
                        IP:
                          type: string
                        port:
                          type: integer
                        weight:
                          type: integer
                      required:
                      - IP
                      - port
                      - weight
                      type: object
                    type: array
                  protocol:
                    type: string
                  targetGroupID:
                    type: string
                  targetGroupName:
                    type: string
                type: object
            required:
            - loadbalancerID
            - port
            - protocol
            type: object
          status:
            description: ListenerStatus defines the observed state of Listener
            properties:
              healthStatus:
                description: ListenerHealthStatus health status of listener
                properties:
                  rules:
                    items:
                      description: ListenerRuleHealthStatus rule health status of
                        listener
                      properties:
                        backends:
                          items:
                            description: ListenerBackendHealthStatus backend health
                              status of listener
                            properties:
                              healthStatus:
                                type: boolean
                              healthStatusDetail:
                                type: string
                              ip:
                                type: string
                              port:
                                type: integer
                              targetID:
                                type: string
                            required:
                            - healthStatus
                            - healthStatusDetail
                            - ip
                            - port
                            - targetID
                            type: object
                          type: array
                        domain:
                          type: string
                        path:
                          type: string
                      required:
                      - domain
                      - path
                      type: object
                    type: array
                type: object
              ingress:
                type: string
              listenerID:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
              msg:
                type: string
              portpool:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
