---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: portpools.networkextension.bkbcs.tencent.com
spec:
  group: networkextension.bkbcs.tencent.com
  names:
    kind: PortPool
    listKind: PortPoolList
    plural: portpools
    singular: portpool
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PortPool is the Schema for the portpools API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PortPoolSpec defines the desired state of PortPool
            properties:
              listenerAttribute:
                description: IngressListenerAttribute attribute for listener
                properties:
                  awsAttribute:
                    description: aws targetGroup attributes, https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyTargetGroupAttributes.html
                    items:
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  healthCheck:
                    description: ListenerHealthCheck health check setting for listener
                    properties:
                      enabled:
                        type: boolean
                      healthCheckProtocol:
                        type: string
                      healthNum:
                        type: integer
                      httpCheckMethod:
                        type: string
                      httpCheckPath:
                        type: string
                      httpCode:
                        type: integer
                      httpCodeValues:
                        description: HTTPCodeValues specifies a set of HTTP response
                          status codes of health check. You can specify multiple values
                          (for example, "200,202") or a range of values (for example,
                          "200-299"). https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.17.0/types#Matcher
                        type: string
                      intervalTime:
                        type: integer
                      timeout:
                        type: integer
                      unHealthNum:
                        type: integer
                    type: object
                  lbPolicy:
                    type: string
                  sessionTime:
                    type: integer
                type: object
              poolItems:
                items:
                  description: PortPoolItem item of port pool
                  properties:
                    endPort:
                      format: int32
                      maximum: 65535
                      minimum: 1
                      type: integer
                    itemName:
                      maxLength: 128
                      minLength: 1
                      type: string
                    loadBalancerIDs:
                      items:
                        type: string
                      type: array
                    segmentLength:
                      format: int32
                      type: integer
                    startPort:
                      format: int32
                      maximum: 65535
                      minimum: 1
                      type: integer
                  required:
                  - endPort
                  - itemName
                  - loadBalancerIDs
                  - startPort
                  type: object
                type: array
            required:
            - poolItems
            type: object
          status:
            description: PortPoolStatus defines the observed state of PortPool
            properties:
              poolItems:
                items:
                  description: PortPoolItemStatus status of a port pool item
                  properties:
                    endPort:
                      format: int32
                      type: integer
                    itemName:
                      type: string
                    loadBalancerIDs:
                      items:
                        type: string
                      type: array
                    message:
                      type: string
                    poolItemLoadBalancers:
                      items:
                        description: IngressLoadBalancer loadbalancer for ingress
                        properties:
                          awsLBType:
                            type: string
                          dnsName:
                            type: string
                          ips:
                            items:
                              type: string
                            type: array
                          loadbalancerID:
                            type: string
                          loadbalancerName:
                            type: string
                          region:
                            type: string
                          scheme:
                            type: string
                          type:
                            type: string
                        type: object
                      type: array
                    segmentLength:
                      format: int32
                      type: integer
                    startPort:
                      format: int32
                      type: integer
                    status:
                      type: string
                  required:
                  - endPort
                  - itemName
                  - message
                  - segmentLength
                  - startPort
                  - status
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
