---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: portbindings.networkextension.bkbcs.tencent.com
spec:
  group: networkextension.bkbcs.tencent.com
  names:
    kind: PortBinding
    listKind: PortBindingList
    plural: portbindings
    singular: portbinding
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PortBinding is the Schema for the portbindings API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PortBindingSpec defines the desired state of PortBinding
            properties:
              portBindingList:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                items:
                  description: PortBindingItem defines the port binding item
                  properties:
                    endPort:
                      type: integer
                    listenerAttribute:
                      description: IngressListenerAttribute attribute for listener
                      properties:
                        awsAttribute:
                          description: aws targetGroup attributes, https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyTargetGroupAttributes.html
                          items:
                            properties:
                              key:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        healthCheck:
                          description: ListenerHealthCheck health check setting for
                            listener
                          properties:
                            enabled:
                              type: boolean
                            healthCheckProtocol:
                              type: string
                            healthNum:
                              type: integer
                            httpCheckMethod:
                              type: string
                            httpCheckPath:
                              type: string
                            httpCode:
                              type: integer
                            httpCodeValues:
                              description: HTTPCodeValues specifies a set of HTTP
                                response status codes of health check. You can specify
                                multiple values (for example, "200,202") or a range
                                of values (for example, "200-299"). https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.17.0/types#Matcher
                              type: string
                            intervalTime:
                              type: integer
                            timeout:
                              type: integer
                            unHealthNum:
                              type: integer
                          type: object
                        lbPolicy:
                          type: string
                        sessionTime:
                          type: integer
                      type: object
                    loadBalancerIDs:
                      items:
                        type: string
                      type: array
                    poolItemLoadBalancers:
                      items:
                        description: IngressLoadBalancer loadbalancer for ingress
                        properties:
                          awsLBType:
                            type: string
                          dnsName:
                            type: string
                          ips:
                            items:
                              type: string
                            type: array
                          loadbalancerID:
                            type: string
                          loadbalancerName:
                            type: string
                          region:
                            type: string
                          scheme:
                            type: string
                          type:
                            type: string
                        type: object
                      type: array
                    poolItemName:
                      type: string
                    poolName:
                      type: string
                    poolNamespace:
                      type: string
                    protocol:
                      type: string
                    rsStartPort:
                      type: integer
                    startPort:
                      type: integer
                  required:
                  - endPort
                  - poolItemName
                  - poolName
                  - poolNamespace
                  - protocol
                  - rsStartPort
                  - startPort
                  type: object
                type: array
            type: object
          status:
            description: PortBindingStatus defines the observed state of PortBinding
            properties:
              portPoolBindStatusList:
                items:
                  description: PortBindingStatusItem port binding item status
                  properties:
                    endPort:
                      type: integer
                    poolItemName:
                      type: string
                    portPoolName:
                      type: string
                    portPoolNamespace:
                      type: string
                    startPort:
                      type: integer
                    status:
                      description: Status is single pool item status
                      type: string
                  required:
                  - endPort
                  - poolItemName
                  - portPoolName
                  - portPoolNamespace
                  - startPort
                  - status
                  type: object
                type: array
              status:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file 整体Pod绑定的状态, NotReady, PartialReady, Ready'
                type: string
              updateTime:
                type: string
            required:
            - status
            - updateTime
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
