apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bcs-bscp.fullname" . }}-authserver
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: bcs-bscp-authserver
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.authserver.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: bcs-bscp-authserver
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: bcs-bscp-authserver
        values-hash: "{{ toYaml .Values.config | sha256sum | trunc 63 }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bcs-bscp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: bcs-bscp:latest
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IPs # ipv6双栈
              valueFrom:
                fieldRef:
                  fieldPath: status.podIPs
            - name: bcsEtcdHost
              value: bcs-bscp-etcd:2379
          ports:
            - name: grpc
              containerPort: 9513
              protocol: TCP
            - name: http
              containerPort: 9613
              protocol: TCP
          command:
            - /bk-bscp/bk-bscp-authserver/bk-bscp-authserver
          args:
            - --bind-ip=$(POD_IP)
            - --config-file=/bk-bscp/bk-bscp-authserver/etc/auth_server.yaml
            - --config-file=/etc/bcs-bscp/bcs_bscp.yaml
            - --disable-auth
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
          - name: config
            mountPath: /etc/bcs-bscp
          {{- if eq .Values.credentials.enabled true }}
          - name: etcd-certs
            mountPath: /data/bcs/cert/etcd
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        configMap:
          name: bcs-bscp
      {{- if eq .Values.credentials.enabled true }}
      - name: etcd-certs
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: ca.crt
                path: etcd-ca.pem
              - key: tls.crt
                path: etcd.pem
              - key: tls.key
                path: etcd-key.pem
              name: bcs-etcd-certs
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
