{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcs-drplan-controller.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-drplan-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  type: {{ .Values.metrics.type }}
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "bcs-drplan-controller.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bcs-drplan-controller.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bcs-drplan-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "bcs-drplan-controller.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
