# This rule is not used by the project bcs-drplan-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dr.bkbcs.tencent.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bcs-drplan-controller
    app.kubernetes.io/managed-by: kustomize
  name: drworkflow-admin-role
rules:
- apiGroups:
  - dr.bkbcs.tencent.com
  resources:
  - drworkflows
  verbs:
  - '*'
- apiGroups:
  - dr.bkbcs.tencent.com
  resources:
  - drworkflows/status
  verbs:
  - get
