# Default values for bcs-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: ""
  repository: /bcs/bcs-storage
  #tag: ""
  pullPolicy: Always
env:
  BK_BCS_bcsZkHost: "127.0.0.1:2181"
  BK_BCS_mongodbHost: "127.0.0.1:27017"
  BK_BCS_mongodbUsername: root
  #encrypted by cryptool
  BK_BCS_mongodbPassword: ""
  BK_BCS_ConfigDbHost: "127.0.0.1:27017"
  BK_BCS_ConfigDbUsername: root
  #encrypted by cryptool
  BK_BCS_ConfigDbPassword: ""
  #oplog.$main when mongodb running in single node
  #oplog.rs when mongodb running in cluster mode
  BK_BCS_mongodbOplogCollection: "oplog.$main"
  BK_BCS_queueConfig: ""
  BK_BCS_queueFlag: ""
  BK_BCS_queueKind: ""
  BK_BCS_resource: ""
  BK_BCS_queueAddress: ""
  BK_BCS_bcsStoragePort: "50024"
  BK_BCS_bcsStorageMetricPort: "50025"
  BK_BCS_log_dir: /data/bcs/logs/bcs
  BK_BCS_pid_dir: "./"
  #default in directory /data/bcs/bcs-storage/
  BK_BCS_storageDbConfig: "./storage-database.conf"
  BK_BCS_eventMaxDay: "7"
  BK_BCS_eventMaxCap: "10000"
  BK_BCS_alarmMaxDay: "7"
  BK_BCS_alarmMaxCap: "10000"
  BK_BCS_caFile: "/data/bcs/cert/bcs/bcs-ca.crt"
  BK_BCS_serverCertFile: "/data/bcs/cert/bcs/bcs-server.crt"
  BK_BCS_serverKeyFile: "/data/bcs/cert/bcs/bcs-server.key"
  BK_BCS_CONFIG_TYPE: "render"
  BK_BCS_bcsEtcdFeature: "true"
  BK_BCS_bcsEtcdHost: "127.0.0.1:2379"
  BK_BCS_bcsEtcdCAFile: /data/bcs/cert/etcd/etcd-ca.pem
  BK_BCS_bcsEtcdCertFile: /data/bcs/cert/etcd/etcd.pem
  BK_BCS_bcsEtcdKeyFile: /data/bcs/cert/etcd/etcd-key.pem
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "bcs-storage"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}

tolerations: []

affinity: {}


#service part
service:
  type: NodePort
  port: 31024

#ingress part
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
