---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: bcsnetips.netservice.bkbcs.tencent.com
spec:
  group: netservice.bkbcs.tencent.com
  names:
    kind: BCSNetIP
    listKind: BCSNetIPList
    plural: bcsnetips
    singular: bcsnetip
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BCSNetIP is the Schema for the bcsnetips API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BCSNetIPSpec defines the desired state of BCSNetIP
            properties:
              gateway:
                description: 网段网关
                type: string
              mask:
                description: 网段掩码
                type: integer
              net:
                description: 所属网段
                type: string
            required:
            - gateway
            - mask
            - net
            type: object
          status:
            description: BCSNetIPStatus defines the observed state of BCSNetIP
            properties:
              containerID:
                description: 容器ID
                type: string
              fixed:
                description: 是否被用作固定IP
                type: boolean
              host:
                description: 对应主机信息
                type: string
              ipClaimKey:
                description: BCSNetIPClaim信息，格式为"命名空间/名称"
                type: string
              keepDuration:
                type: string
              phase:
                description: Active --已使用，Available --可用, Reserved --保留
                type: string
              podName:
                type: string
              podNamespace:
                type: string
              updateTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
