---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: bcsnetpools.netservice.bkbcs.tencent.com
spec:
  group: netservice.bkbcs.tencent.com
  names:
    kind: BCSNetPool
    listKind: BCSNetPoolList
    plural: bcsnetpools
    singular: bcsnetpool
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: BCSNetPool is the Schema for the bcsnetpools API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BCSNetPoolSpec defines the desired state of BCSNetPool
            properties:
              availableIPs:
                description: 可用的IP
                items:
                  type: string
                type: array
              gateway:
                description: 网段网关
                type: string
              hosts:
                description: 对应主机列表
                items:
                  type: string
                type: array
              mask:
                description: 网段掩码
                type: integer
              net:
                description: 网段
                type: string
            required:
            - gateway
            - mask
            - net
            type: object
          status:
            description: BCSNetPoolStatus defines the observed state of BCSNetPool
            properties:
              phase:
                description: Initializing --初始化中，Normal --正常
                type: string
              updateTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
