
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: cloudips.cloud.bkbcs.tencent.com
spec:
  group: cloud.bkbcs.tencent.com
  names:
    kind: CloudIP
    listKind: CloudIPList
    plural: cloudips
    singular: cloudip
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: CloudIP is the Schema for the cloudips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CloudIPSpec defines the desired state of CloudIP
          properties:
            address:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            cluster:
              type: string
            containerID:
              type: string
            eniID:
              type: string
            host:
              type: string
            isFixed:
              type: boolean
            keepDuration:
              type: string
            namespace:
              type: string
            podName:
              type: string
            region:
              type: string
            subnetCidr:
              type: string
            subnetID:
              type: string
            vpcID:
              type: string
            workloadKind:
              type: string
            workloadName:
              type: string
          required:
          - address
          - cluster
          - containerID
          - eniID
          - host
          - isFixed
          - keepDuration
          - namespace
          - podName
          - region
          - subnetCidr
          - subnetID
          - vpcID
          - workloadKind
          - workloadName
          type: object
        status:
          description: CloudIPStatus defines the observed state of CloudIP
          properties:
            createTime:
              type: string
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
            updateTime:
              type: string
          required:
          - createTime
          - status
          - updateTime
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
