apiVersion: dr.bkbcs.tencent.com/v1alpha1
kind: DRWorkflow
metadata:
  labels:
    app.kubernetes.io/name: bcs-drplan-controller
    app.kubernetes.io/managed-by: kustomize
  name: drworkflow-sample
spec:
  # TODO(user): Add fields here
