apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: appnodes.mesh.bmsf.tencent.com
spec:
  group: mesh.bmsf.tencent.com
  names:
    kind: AppNode
    plural: appnodes
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            index:
              description: node key, pod instance name/taskgroup name
              maxLength: 200
              minLength: 1
              type: string
            network:
              description: app node network mode
              type: string
            nodeIP:
              description: node ip address
              type: string
            ports:
              description: port info for container
              items:
                properties:
                  name:
                    description: name for port, must equal to one service port
                    maxLength: 100
                    minLength: 4
                    type: string
                  nodeport:
                    description: node port
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  protocol:
                    description: protocol for this port
                    enum:
                    - tcp
                    - udp
                    - http
                    type: string
                  proxyport:
                    description: proxy port if exists
                    format: int64
                    maximum: 65535
                    minimum: -10
                    type: integer
                required:
                - name
                - protocol
                - nodeport
                type: object
              type: array
            proxyIP:
              description: proxy ip address for this node
              type: string
            version:
              description: node version, like v1, v1.1, v12.01.1, come from env[BCS_DISCOVERY_VERSION]
              type: string
            weight:
              description: node weight, it's a Relative value
              maximum: 100
              minimum: 0
              type: uint
          required:
          - index
          - nodeIP
          type: object
        status:
          properties:
            lastUpdateTime:
              description: last updated timestamp
              format: date-time
              type: string
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
