{{ include "common.metadata" . }}
- - group:
      - - container:
            grid-template-columns: "1fr 70px 1fr 70px"
          group:
            - [ "cnt", "." ]
            - [ "updateStrategy" ]
            - [ "maxSurge", "msUnit", "maxUnavailable", "muaUnit" ]
            - [ "minReadySecs", "progressDeadlineSecs" ]
          prop: replicas
      {{- include "workload.affinity" . | nindent 6 }}
      {{- include "workload.toleration" . | nindent 6 }}
      {{- include "workload.networking" . | indent 6 }}
      {{- include "workload.security" . | indent 6 }}
      {{- include "workload.readinessGates" . | indent 6 }}
      {{- include "workload.other" . | indent 6 }}
    prop: spec
{{- include "container.containerGroup" . }}
{{- include "workload.volume" . }}
